name: Release docs

# on:
#   push:
#     branches:
#     - main
on: pull_request

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'
    - name: Setup node & sass
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: install sass
      run: npm install -g sass
    - name: Restore tools
      working-directory: ./docs/
      run: dotnet tool restore
    - name: Run Fornax
      working-directory: ./docs/
      run: dotnet fake build -t Docs
    # - name: Build
    #   working-directory: ./docs/src
    #   run: dotnet fornax build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_public
        publish_branch: gh-pages
        force_orphan: true
        cname: saturnframework.org
