name: Release docs

on:
  push:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main

jobs:
  build:

    runs-on: windows-latest
    # runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.408'
    - name: Restore tools
      working-directory: build-docs
      run: dotnet tool restore
    - name: Run Fornax
      working-directory: build-docs
      run: dotnet run -- Docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build-docs/docs/_public
        publish_branch: gh-pages
        force_orphan: true
        cname: saturnframework.org
